### ISSUE TITLE
Game had some issues with Python 3 and Kivy 1.10

### ISSUE THREAD

**Issue by madSec** [oOo0oOo/RocketKite#1]
Hi,

Thanks a lot for this awesome game! I am using it to learn Kivy and improve my Python skills. It was easy to port it to Python 3 though there were two small issues when running it with the newer Python 3 reasy Kivy 1.10. 

I managed to fix the issues in a local git branch, if you are interested I can upload the branch to your repository. Alternatively I am happy to upload it to my own private GitHub account so you can see the changes I made there.

Best wishes,

Manuel

**Comment by oOo0oOo** [comment]
Hi,

I'm glad this repository is useful to you. 
Honestly, I haven't looked at it in a while ;-)
Feel free to submit a pull request, I think this code is more useful to people if it runs in Python 3 and with an up to date version of kivy.

Thanks!

**Comment by madSec** [comment]
Hi,

Just submitted a pull request with my changes.

Best wishes,
Manuel

**Comment by oOo0oOo** [comment]
I merged your pull request into the master branch. Thanks for the effort!

**Comment by madSec** [comment]
You are welcome, I'm glad I could help!
